public class ListCollection {
   // Bu metot parametre olarak bir isim listesi alsin.
   // Bu isimleri tek tek yazdirsin
   public static void printNames(list<string> adList) {
    // listemizin bosmu dolumu oldugunu iki sekilde kontrol ederiz
    //1
    if (adList.size()>0){
        integer counter=1;
        for (string eacName : adList) {

            System.debug('for dongusu'+ counter +' defa dondu');
            System.debug(eacName);
            counter++;

        }
    }
}
        public static decimal listTopla(List<Decimal> decList) {
            Decimal sum;

            if (condition) {
                
            }



            return sum;


            
        }




}

            
        
