public  class practice12 {
     
        public static List <devturkish> studentsL= new List<devturkish>();

        
        public static void students(){
            devturkish ss1= new devturkish('Esma', 'Toprak', '10B', true);
            studentsL.add(ss1);

            devturkish ss2= new devturkish('Tolga', 'Mermer', '9A', false);
            studentsL.add(ss2);

            devturkish ss3= new devturkish('Ali', 'Kaya', '11B', true);
            studentsL.add(ss3);


            devturkish ss4= new devturkish('Cem', 'Gumus', '16B', true);
            studentsL.add(ss4);
}

 

    
}
